In [3]:
import numpy as np

x = np.array([1,2,3])
print(x)

[1 2 3]


In [4]:
# 크키가 (1,3)인 2차원
np.array([1,2,3])

array([1, 2, 3])

In [6]:
# 크키가 (1,3)인 2차원
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [8]:
from scipy import linalg
s = np.array([2,3,1])
print(s)

[2 3 1]


In [9]:
# 단위 벡터

s / linalg.norm(s)

array([0.53452248, 0.80178373, 0.26726124])

In [11]:
# Norm
x = np.array([1,-3])
x / linalg.norm(x)

array([ 0.31622777, -0.9486833 ])

In [12]:
# Norm 2
x / (x**2).sum()**0.5

array([ 0.31622777, -0.9486833 ])

In [13]:
# 영벡터 (zeros())

In [14]:
np.zeros(5) # 실수로 반환

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5).shape

(5,)

In [16]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [17]:
# 선형 독립, 선형 종속
# Rank

# matrix_rank()

x = np.array([[2,7],[5,1]])
np.linalg.matrix_rank(x)

2

In [19]:
x_2 = np.array([[2,4],[3,6]])
np.linalg.matrix_rank(x_2)

1

In [20]:
x_3 = np.array([[1,2],[3,5]])
np.linalg.matrix_rank(x_3)

2

In [23]:
# 벡터의 내적과 외적

x = [2,3]
y = [3,1]

# zip 함수

z = [i+j for i,j in zip(x,y)]
print(z)

[5, 4]


In [24]:
# zip 함수
list(zip([1,2,3],[4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [25]:
list(zip([1,2,3],[4,5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [26]:
z_2 = [i - j for i, j in zip(x,y)]
print(z_2)

[-1, 2]


In [27]:
# 벡터의 곱셈(inner porduct, outer product)

x = [3,4]
c = 8

z = [c*i for i in x]
print(z)

[24, 32]


In [28]:
# 내적(inner product)

u = np.array([6,6])
v = np.array([12,0])

np.dot(u,v) # (1, 2) * (2, 1) = (1, 1) 이기 때문에 스칼라 값으로 나온다.

72