## 화면 출력 (print)

In [1]:
print("Hello World")

Hello World


In [2]:
print("Python을 시작합니다\n안녕하세요?")

Python을 시작합니다
안녕하세요?


In [3]:
pi=3.1415926535
print(pi)

3.1415926535


In [4]:
hello="안녕하세요"
print(hello)

안녕하세요


In [6]:
name="경상대학교"
print("학교이름은 {}입니다.".format(name))

학교이름은 경상대학교입니다.


# 숫자(numerics)

In [7]:
# 데이터 형태
# d: 정수 (int)
# s: 문자 (str)
# f: 실수 (float)

In [8]:
type(10)

int

In [9]:
type(3.14)

float

In [10]:
type(7+5j)

complex

In [11]:
10+4

14

In [12]:
10-4

6

In [13]:
10*4

40

In [14]:
10**2

100

In [15]:
10/4

2.5

In [16]:
10//4

2

In [17]:
10%4

2

In [18]:
10>4

True

In [19]:
10<4

False

In [20]:
10==4

False

In [21]:
10!=4

True

In [22]:
10>=4

True

In [23]:
10<=4

False

In [26]:
a=10
b=4
c=2

In [27]:
a+b

14

In [28]:
a>=b

True

In [29]:
a=True
b=False
(a and b)

False

In [30]:
a=True
b=False
(a or b)

True

In [31]:
a=True
b=False
not b

True

In [32]:
a=True
b=False
not(a and b)

True

In [33]:
a=True
b=False
not(a or b)

False

## 문자열 자료형 (String)

In [34]:
# 문자열 붙이기 (concatenation)
C3 = "Life"
C4 = "is"
C5 = "too"
C6 = "short"
C7 = C3 + C4 + C5 + C6
C8 = C3 + " " + C4 + " " + C5 + " " + C6
print(C7)
print(C8)

Lifeistooshort
Life is too short


In [35]:
# 문자열 인덱싱 (indexing)
C1 = "HELLO PYTHON"  
C2 = "안녕하세요 파이썬씨?우리 잘 해봅시다"
print(C1[0]) #C1의 0번째 문자
print(C1[-2]) #C1의 끝에서 2번째 문자
print(C2[2]) #C2 2번째 문자
print(C2[-3]) #C2 끝에서 3번째 문자

H
O
하
봅


In [38]:
# 문자열 슬라이싱 (slicing)
C2 = "어서와 파이썬은 처음이지?\n나도 처음이야"
print(C2[7])   # 7번째 문자 추출
print(C2[4:7]) #4번째 문자부터 6번째까지
print(C2[:6]) #처음부터 5번째까지
print(C2[-6:])#끝에서 6번째부터 끝까지

은
파이썬
어서와 파이
도 처음이야


In [39]:
print("어서와 파이썬은 처음이지?\n나도 처음이야")

어서와 파이썬은 처음이지?
나도 처음이야


In [40]:
# 문자열 찾기 (finding)
C2 = "어서와 파이썬은 처음이지?\n나도 처음이야"
print(C2.index('와')) # C2문장에서 '와'의 위치 2번째 (0부터 계산)
print(C2.find('파')) #C2문장에서 '파'의 위치는 4번째 (공백도 계산)

2
4


In [45]:
#my 문자열 찾기 (finding)
c2 = '어서와 메이플은 처음이지?\n나는 고인물이야'
print(c2.index('메'))
print(c2.find('메'))

4
4


In [41]:
# 대/소문자 바꾸기 (convert to uppercase/lowercase)
C1 = "HELLO PYTHON"
C6 = "short"
print(C1.lower())
print(C6.upper())

hello python
SHORT


In [46]:
# my 대/소문자 바꾸기 (convert to uppercase/lowercase)
c1 = 'maple'
c2 = 'STORY'
print(c1.upper(), c2.lower())

MAPLE story


In [42]:
# 공백 지우기 (strip, remove spaces)
C9 = " HELLO "
print(C9.lstrip()) #왼쪽 공백 제거
print(C9.rstrip()) # 오른쪽 공백 제거
print(C9.strip()) #양쪽 공백제거

HELLO 
 HELLO
HELLO


In [47]:
# my 공백 지우기 (strip, remove spaces)
c9 = " maple "
print(c9.strip())
print(c9.rstrip())
print(c9.lstrip())

maple
 maple
maple 


In [43]:
# 문자열 찾아 바꾸기 (replace)
C10 = "한국대학교"
print(C10.replace("한국", "Korea"))

Korea대학교


In [49]:
# my 문자열 찾아 바꾸기 (replace)
c10 = 'maple story2'
print(c10.replace('2',''))

maple story


In [44]:
# 문자열 나누기 (split)
C11 = "A:B:C:D"
print(C11.split(':')) #':'를 기준으로 문자열 나누기

['A', 'B', 'C', 'D']


In [50]:
# my 문자열 나누기 (split)
c11 = 'M:A:P:L:E'
print(c11.split(':'))

['M', 'A', 'P', 'L', 'E']


## 목록(List)과 튜플(tuple)

In [51]:
L1 = [1, 2, 3, 4]
L2 = ['Life', 'is', 'too', 'short']
L3 = [1, 2, 'Python']
L4 = [1, 2, ['Life', 'Python']]

In [52]:
# 리스트 슬라이싱 (list slicing)
L1 = [1, 2, 3, 4]
L4 = [1, 2, ['Life', 'Python']]

print(L1[0])#L1의 첫번째 요소 추출
print(L1[1]+L1[3]) #L1 두번째 요소(2)+L1의 네번째 요소(4) 
print(L4[-1]) #L4 끝에서 첫번째 요소 추출
print(L4[-1][0]) #L4 끝에서 첫번째 요소(['Life', 'Python']) 중 첫번째 

1
6
['Life', 'Python']
Life


In [ ]:
# my 리스트 슬라이싱 (list slicing)
l1 = [1,2,3,4]
l4 = [1,2,['Life', 'Python']]

print(l1[0])
print(l1[1]+l1[3])
print(l3[-1])
print(l1[0])

In [53]:
# 리스트 연산자 (더하기, 반복하기)
L1 = [1, 2, 3, 4]
L5 = [4, 5, 6, 7]
print(L1+L5) #L1과 L5 더하기
print(L1*3)#L1 3번 반복

[1, 2, 3, 4, 4, 5, 6, 7]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [54]:
# 리스트에 요소 삽입
L7 = ['a', 'b', 'c', 'd', 'e', 'f']
L7.append('g')
print(L7)

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [55]:
# 리스트에 요소 삽입
L8 = [1, 3, 2, 4, 5, 7, 8, 10, 6]
L8.insert(2, 9)#L8의 세번째 요소 9삽입
print(L8)

[1, 3, 9, 2, 4, 5, 7, 8, 10, 6]


In [58]:
# 리스트간 합치기
L10 = [1, 2, 3, 4, 5]
L11 = [6, 7, 8, 9, 10]
L10.extend(L11)
L10+=L11
print(L10)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 6, 7, 8, 9, 10]


In [59]:
# 리스트간 합치기
L10 = [1, 2, 3, 4, 5]
L11 = [6, 7, 8, 9, 10]
L10+=L11
print(L10)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [60]:
# 리스트 하나의 값 수정하기
L6 = [1, 2, 4, 3, 5, 7, 7, 8]
L6[5]=6 #6번째 요소의 값을 6으로 수정
print(L6)

[1, 2, 4, 3, 5, 6, 7, 8]


In [61]:
# 리스트에 여러 값 수정하기 (범위)
L6 = [1, 2, 4, 3, 5, 7, 7, 8]
L6[2:4] = [3, 4]#3번째에서 4번째 사이의 요소 값을 3, 4로 수정
print(L6)

[1, 2, 3, 4, 5, 7, 7, 8]


In [62]:
# 리스트에서 요소 삭제
L6 = [1, 2, 4, 3, 5, 7, 7, 8]
del L6[7] #8번째 요소 삭제
print(L6)

[1, 2, 4, 3, 5, 7, 7]


In [63]:
# 리스트에서 요소 삭제
L6 = [1, 2, 4, 3, 5, 7, 7, 8]
L6.pop(7) #8번째 요소 삭제
print(L6)

[1, 2, 4, 3, 5, 7, 7]


In [64]:
# 리스트에서 요소의 개수 확인
L9 = [1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4]
print(L9.count(1)) #L9에서 1이 몇 개인가 계산
print(L9.count(2))#L9에서 2가 몇 개인가 계산

2
3


In [65]:
# 리스트 정렬
L8 = [1, 3, 2, 4, 5, 7, 8, 10, 6]
L8.sort() #오름차순으로 정렬
print(L8)

L8 = [1, 3, 2, 4, 5, 7, 8, 10, 6]
L8.sort(reverse=True) #내림차순으로 정렬
print(L8)

[1, 2, 3, 4, 5, 6, 7, 8, 10]
[10, 8, 7, 6, 5, 4, 3, 2, 1]


In [66]:
# 리스트를 역순으로 정렬
L8 = [1, 3, 2, 4, 5, 7, 8, 10, 6]
L8.reverse()
print(L8)

[6, 10, 8, 7, 5, 4, 2, 3, 1]


In [67]:
#리스트를 튜플로 변환
L9=tuple(L8)
L9

(6, 10, 8, 7, 5, 4, 2, 3, 1)

In [68]:
type(L8)

list

In [69]:
type(L9)

tuple

In [76]:
# 튜플(tuple)
T1 = (1, 2, 3, 4, 5)
T2 = ('a', 'b', 'c', 'd', 'e')
L1 = ['a', 'b', 'c', 'd', 'e']
print(type(T1)) #T1의 자료유형 표기
print(type(T2))#T2의 자료유형 표기
print(type(L1))#L1의 자료유형 표기

<class 'tuple'>
<class 'tuple'>
<class 'list'>


## 사전 (Dictionary)

In [70]:
# 딕셔너리(dictionary)
D1 = {'name': 'KIM', 'birth': '2003', 'height': '175'}
print(D1['name'])

KIM


In [80]:
d1 = {'name':'KIM', 'birth': '1997', 'height':'181'}
print(d1['name'])

KIM


In [71]:
D1['weight']='60'#D1에 key 'weight'와 value'60'추가
print(D1)

{'name': 'KIM', 'birth': '2003', 'height': '175', 'weight': '60'}


In [82]:
d1['weight'] = '85'
print(d1)

{'name': 'KIM', 'birth': '1997', 'height': '181', 'weight': '85'}


In [72]:
D1['height']='180'#'height'의 값을 '180'으로 수정
print(D1)

{'name': 'KIM', 'birth': '2003', 'height': '180', 'weight': '60'}


In [83]:
d1['height'] = '185'
print(d1)

{'name': 'KIM', 'birth': '1997', 'height': '185', 'weight': '85'}


In [73]:
del D1['name'] #D1에서 'name' 삭제
print(D1)

{'birth': '2003', 'height': '180', 'weight': '60'}


In [85]:
del d1['name']
print(d1)

{'birth': '1997', 'height': '185', 'weight': '85'}


In [75]:
D1.keys()
D1.values()

dict_values(['2003', '180', '60'])

In [76]:
D1key=list(D1.keys()) #D1의 key이름 목록 만들기
print(D1key)

['birth', 'height', 'weight']


In [86]:
d1key=list(d1.keys()) #D1의 key이름 목록 만들기
print(d1key)

['birth', 'height', 'weight']


In [77]:
D1value=list(D1.values())#D1의 value값 목록 만들기
print(D1value)

['2003', '180', '60']


In [87]:
d1val = list(d1.values())
print(d1val)

['1997', '185', '85']


In [78]:
# Key 존재 여부 확인
print('nember' in D1) #D1에 'number'라는 key가 있는지 여부 확인
print('weight' in D1) #D1에 'weight'라는 key가 있는지 여부 확인

False
True


In [88]:
print('asd' in d1)
print('weight' in d1)

False
True


## 다차원 배열 (ndarray)

In [89]:
# 배열 만들기
import numpy as np
V1=np.array([1, 2, 3, 4])
print(V1)

[1 2 3 4]


In [90]:
V1 = np.arange(5) #처움(0)부터 5번째 숫자(4)까지의 숫자 배열
print(V1)

[0 1 2 3 4]


In [93]:
V4 = np.arange(1, 10, 2)
print(V4)

[1 3 5 7 9]


In [94]:
V4 = np.arange(1, 10, 2) ** 2 #1부터10까지 2 간격 수(1, 3, 5, 7, 9)의 제곱
print(V4)

[ 1  9 25 49 81]


In [95]:
V5 = np.arange(1, 10, 2) ** 3 #1부터10까지 2 간격 수(1, 3, 5, 7, 9)의 세제곱
print(V5)

[  1  27 125 343 729]


In [96]:
# 배열 만들기 (연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정)
V2 = np.arange(3, 10, 2, dtype=int) #3부터 10사이 2간격의 정수
print(V2)

[3 5 7 9]


In [97]:
# 배열 만들기 (연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정)
V3 = np.arange(3.5, 10.5, 2, dtype=float) # 3.5부터 10.5사이 2간격의 실수
print(V3)

[3.5 5.5 7.5 9.5]


In [98]:
# 배열 합치기
V6 = V4+V5
print(V6)

[  2  36 150 392 810]


In [99]:
# 행렬 만들기
V1=np.arange(12)#0부터 12번째
print(V1)
V2=V1.reshape(2, 6)#V1 2행 6열, 행부터 채워넣음
print(V2)
V3=V1.reshape(2, 6, order='F') #2행 6열, 열부터 채워넣음
print(V3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [100]:
# -1의 의미는 알아서 맞춰달라는 이야기다.
V1.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [101]:
# 행렬의 곱
V1=np.arange(1,5).reshape(2,2) #1부터 4번째 2행2열, 행부터 채움
print(V1)

[[1 2]
 [3 4]]


In [102]:
# 요소끼리 곱해진다.
print(V1*V1)#V1과 V1의 요소끼리 단순하게 곱한다

[[ 1  4]
 [ 9 16]]


In [103]:
print(np.dot(V1, V1)) #V1과 V1의 행렬의 곱셈방식을 적용하여 계산

[[ 7 10]
 [15 22]]


In [104]:
V3 = np.arange(3.5, 10.5, 2, dtype=float)
print(V3)
V6 = np.arange(1,5).reshape(2,2)
print(V6)
print(np.amax(V3)) # 최대값 반환
print(np.amin(V6)) # 최소값 반환
print(V3.dtype) # V3의 데이터 타입
print(V6.shape) # V6의 행, 열, 차원 확인

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
(2, 2)


In [105]:
# np.matrix에서 행렬 만드는 법
M1=np.matrix([[1, 2], [3, 4]])
print(M1)

# np.matrix에서 만든 행렬의 곱
print(M1*M1)

[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


## 조건문 (if)

In [106]:
금액 = 5000
if 금액==5000:
    print("짜장면")

짜장면


In [107]:
금액 = 6000
if 금액 == 5000:
    print("짜장면")
if 10000 > 금액 > 5000:
    print("짬뽕")

짬뽕


In [108]:
금액 = 6000
if 금액 == 5000:
    print("짜장면")
elif 10000 > 금액 > 5000:
    print("짬뽕")

짬뽕


In [109]:
금액 = 4000
if 금액 == 5000:
    print("짜장면")
elif 10000 > 금액 > 5000:
    print("짬뽕")
else:
    print ("죄송해요")

죄송해요


In [110]:
금액 = 4000
if 금액 == 5000:
    print('짜장면')
elif 10000 > 금액> 5000:
    print('짬뽕')
else:
    print("sorry")

sorry


In [111]:
음식메뉴 = ['짜장면', '짬뽕']
if '짜장면' in 음식메뉴:
    print("짜장면이요.")
if '짬뽕' in 음식메뉴:
    print("짬뽕드세요.")
else:
    print("오늘 굶으세요")

짜장면이요.
짬뽕드세요.


In [112]:
음식메뉴 = ['짜장면', '짬뽕']
if '짜장면' in 음식메뉴:
    print("짜장면이요.")
elif '짬뽕' in 음식메뉴:
    print("짬뽕드세요.")
else:
    print("오늘 굶으세요")

짜장면이요.


In [113]:
메뉴 = ['짜장면', '짬뽕']

if '짜장면' in 메뉴:
    print("짜장면이요")
elif '짬뽕' in 메뉴:
    print('짬뽕드세요')
else:
    print('오늘 굶으세요')

짜장면이요


In [114]:
음식메뉴 = ['짬뽕']
if '짜장면' in 음식메뉴:
    print("짜장면이요.")
elif '짬뽕' in 음식메뉴:
    print("짬뽕드세요.")
else:
    print("오늘 굶으세요")

짬뽕드세요.


In [115]:
음식메뉴 = []
if '짜장면' in 음식메뉴:
    print("짜장면이요.")
elif '짬뽕' in 음식메뉴:
    print("짬뽕드세요.")
else:
    print("오늘 굶으세요")

오늘 굶으세요


In [116]:
음식메뉴 = ['군만두']
if '짜장면' in 음식메뉴:
    print("짜장면이요.")
elif '짬뽕' in 음식메뉴:
    print("짬뽕드세요.")
else:
    print("오늘 굶으세요")

오늘 굶으세요


In [117]:
음식메뉴 = ['짜장면', '짬뽕','군만두']
if '짜장면' in 음식메뉴:
    print("짜장면")
if '짬뽕' in 음식메뉴:
    print("짬뽕")
if '군만두' in 음식메뉴:
    print("군만두")

짜장면
짬뽕
군만두


In [118]:
음식메뉴 = ['짜장면', '짬뽕','군만두']
for i in 음식메뉴:
    print(i)

짜장면
짬뽕
군만두


In [119]:
for i in ['짜장면', '짬뽕','군만두']:
    print(i)

짜장면
짬뽕
군만두


In [120]:
중국음식=['짜장면','짬뽕','군만두','탕수육','팔보채']
for 메뉴 in 중국음식:
    if "짜장면" in 메뉴:
        continue       # 짜장면 건너뛰고 차례로 출력
    print(메뉴)

짬뽕
군만두
탕수육
팔보채


In [121]:
중국음식 = ['짜장면','짬뽕','군만두','탕수육','팔보채']
for menu in 중국음식:
    if "짜장면" in menu:
        continue
    print(menu)

짬뽕
군만두
탕수육
팔보채


In [122]:
중국음식=['짜장면','짬뽕','군만두','탕수육','팔보채']
for 메뉴 in 중국음식:
    if "짜장면" in 메뉴:
        pass       # 짜장면부터 차례로 출력
    print(메뉴)

짜장면
짬뽕
군만두
탕수육
팔보채


In [123]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [124]:
for i in range(20):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [127]:
for i in range(20):
    print(i, end =' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [128]:
for i in range(10,20):
    print(i, end=" ")

10 11 12 13 14 15 16 17 18 19 

In [129]:
for i in range(10,20,2):
    print(i, end=" ")

10 12 14 16 18 

In [130]:
for i in range(10,20,2):
    print(i*3, end=" ")

30 36 42 48 54 

In [131]:
for i in range(2, 6):
    for j in range(1, 5):
        print(i+j, end=" ")
    print("")

3 4 5 6 
4 5 6 7 
5 6 7 8 
6 7 8 9 


In [136]:
for i in range(2,6):
    for j in range(1,5):
        print(i+j, end=' ')
    print('')

3 4 5 6 
4 5 6 7 
5 6 7 8 
6 7 8 9 


In [137]:
for i in range(2, 6):
    for j in range(1, 5):
        print("{}+{}={}". format(i,j,i+j), end=" ")
    print("\n")

2+1=3 2+2=4 2+3=5 2+4=6 

3+1=4 3+2=5 3+3=6 3+4=7 

4+1=5 4+2=6 4+3=7 4+4=8 

5+1=6 5+2=7 5+3=8 5+4=9 



In [138]:
for i in range(2, 6):
    for j in range(1, 5):
        print("{}+{}={}". format(i,j,i*j), end=" ")
    print("\n")

2+1=2 2+2=4 2+3=6 2+4=8 

3+1=3 3+2=6 3+3=9 3+4=12 

4+1=4 4+2=8 4+3=12 4+4=16 

5+1=5 5+2=10 5+3=15 5+4=20 

