In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import tree, ensemble
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [3]:
# 데이터 로딩
# 중산층이냐 아니냐를 판펼
pd.read_csv('./middle.csv - middle.csv.csv')

food      book       cul     cloth    travel  status
0   0.263017  0.759435  0.472159  0.365709  0.331119       1
1   0.192398  0.514150  0.222987  0.388257  0.307846       1
2   0.513997  0.448345  0.554666  0.394886  0.363455       0
3   0.387733  0.582956  0.425999  0.349615  0.197456       1
4   0.421674  0.560781  0.430536  0.734413  0.352037       0
..       ...       ...       ...       ...       ...     ...
95  0.170611  0.656753  0.478071  0.319717  0.312484       1
96  0.393424  0.927768  0.239522  0.489993  0.304990       1
97  0.348236  0.758736  0.304017  0.252886  0.245836       1
98  0.378175  0.606787  0.182603  0.473498  0.297998       0
99  0.338647  0.591898  0.267180  0.443084  0.170536       0

[100 rows x 6 columns]

In [4]:
middle = pd.read_csv('./middle.csv - middle.csv.csv')

In [7]:
x = middle.iloc[:,:-1].values
y = middle.iloc[:,-1].values

In [9]:
x.shape, y.shape

((100, 5), (100,))

In [10]:
# 정규화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [11]:
x = scaler.fit_transform(x)

In [13]:
x_regu = x
x_regu

array([[-6.79490582e-01,  2.85452572e-01,  7.69363065e-01,
        -3.92848549e-01,  1.16109560e+00],
       [-1.36649081e+00, -7.93115937e-01, -1.70438786e+00,
        -1.77986086e-01,  7.31897271e-01],
       [ 1.76207947e+00, -1.08247293e+00,  1.58847972e+00,
        -1.14819268e-01,  1.75741834e+00],
       [ 5.33770153e-01, -4.90560785e-01,  3.11090235e-01,
        -5.46207407e-01, -1.30388542e+00],
       [ 8.63949841e-01, -5.88070095e-01,  3.56134286e-01,
         3.12053813e+00,  1.54685944e+00],
       [-9.55034863e-01, -6.56679973e-01,  1.03540717e-02,
         7.84325978e-01,  1.43126140e-01],
       [-1.04290710e+00,  3.24664723e-01,  1.94243500e-01,
         8.05043535e-02, -1.40235462e+00],
       [-5.31724583e-02,  4.88510281e-01,  9.15523136e-01,
         2.84851975e-01,  7.49844332e-01],
       [-2.19010248e-01,  3.83124161e-01,  3.96799407e-01,
        -1.13684875e+00, -1.00538045e+00],
       [ 1.16507338e-01,  1.10917815e+00,  6.44628679e-01,
        -7.93871530e-01

In [23]:
# 랜덤포레스트
classifier = ensemble.RandomForestClassifier(n_estimators=20, max_depth=3, criterion='gini')

In [24]:
classifier.fit(x_regu, y)

RandomForestClassifier(max_depth=3, n_estimators=20)

In [25]:
x_regu, type(x_regu), y, type(y)

(array([[-6.79490582e-01,  2.85452572e-01,  7.69363065e-01,
         -3.92848549e-01,  1.16109560e+00],
        [-1.36649081e+00, -7.93115937e-01, -1.70438786e+00,
         -1.77986086e-01,  7.31897271e-01],
        [ 1.76207947e+00, -1.08247293e+00,  1.58847972e+00,
         -1.14819268e-01,  1.75741834e+00],
        [ 5.33770153e-01, -4.90560785e-01,  3.11090235e-01,
         -5.46207407e-01, -1.30388542e+00],
        [ 8.63949841e-01, -5.88070095e-01,  3.56134286e-01,
          3.12053813e+00,  1.54685944e+00],
        [-9.55034863e-01, -6.56679973e-01,  1.03540717e-02,
          7.84325978e-01,  1.43126140e-01],
        [-1.04290710e+00,  3.24664723e-01,  1.94243500e-01,
          8.05043535e-02, -1.40235462e+00],
        [-5.31724583e-02,  4.88510281e-01,  9.15523136e-01,
          2.84851975e-01,  7.49844332e-01],
        [-2.19010248e-01,  3.83124161e-01,  3.96799407e-01,
         -1.13684875e+00, -1.00538045e+00],
        [ 1.16507338e-01,  1.10917815e+00,  6.44628679e-01,
    

In [26]:
# 실제값

expected = y
expected

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [27]:
# 예측값
predicted = classifier.predict(x_regu)
predicted

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [28]:
print("Accuracy:\n",
     accuracy_score(expected, predicted))
print()
print('Confusion_Matrix:\n',
     confusion_matrix(expected, predicted))

Accuracy:
 0.86

Confusion_Matrix:
 [[17 14]
 [ 0 69]]


## 에이다 부스트 AdaBoost

In [29]:
# base 를 decision tree로 하겠다.
classfier2 = ensemble.AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=3), n_estimators=20)

In [30]:
classfier2.fit(x_regu, y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3),
                   n_estimators=20)

In [31]:
# 분류기 성능 확인

expected2 = y
predicted2 = classfier2.predict(x_regu)

print(predicted2)

[1 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0 1 1
 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0]


In [32]:
print("Accuracy:\n",
     accuracy_score(expected2, predicted2))
print()
print('Confusion_Matrix:\n',
     confusion_matrix(expected2, predicted2))

Accuracy:
 1.0

Confusion_Matrix:
 [[31  0]
 [ 0 69]]
