In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
like=pd.read_csv('./like.csv')
like

말이 많은 정도  책을 좋아하는 정도  여행을 좋아하는 정도  학교성적   키  피부가 좋은 정도  근육질의 정도 호감LABEL
0         30          80           40    40  90         90       50     1타입
1         60          50           70    50  60         60       90     2타입
2         50          40           80    60  50         70       80     2타입
3         90          50           60    30  40         20       30     3타입
4         50          70           30    70  70         80       60     1타입
5         70          30           60    40  40         40       30     3타입
6         40          90           60    60  60         80       60     1타입
7         30          60           90    60  40         70       70     2타입
8         80          40           20    80  60         40       50     3타입
9         50          70           70    50  70         90       50     1타입
10        80          50           60    40  50         40       70     3타입
11        30          70           30    90  70         80       60     1타입
12        40          60           90    60  50         70       80     2타입
13        80          30           50    50  80         40       60     3타입

In [4]:
like.columns = ['talk', 'book', 'travel', 'school', 'tall', 'skin', 'muscle', 'like_level']

In [5]:
like.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   talk        14 non-null     int64 
 1   book        14 non-null     int64 
 2   travel      14 non-null     int64 
 3   school      14 non-null     int64 
 4   tall        14 non-null     int64 
 5   skin        14 non-null     int64 
 6   muscle      14 non-null     int64 
 7   like_level  14 non-null     object
dtypes: int64(7), object(1)
memory usage: 1.0+ KB


In [6]:
# 입력과 target 데이터를 분리

x = np.array(like.drop('like_level', axis=1))
print(x.shape)

(14, 7)


In [7]:
y = np.array(like.like_level)
y.shape

(14,)

In [8]:
x, y

(array([[30, 80, 40, 40, 90, 90, 50],
        [60, 50, 70, 50, 60, 60, 90],
        [50, 40, 80, 60, 50, 70, 80],
        [90, 50, 60, 30, 40, 20, 30],
        [50, 70, 30, 70, 70, 80, 60],
        [70, 30, 60, 40, 40, 40, 30],
        [40, 90, 60, 60, 60, 80, 60],
        [30, 60, 90, 60, 40, 70, 70],
        [80, 40, 20, 80, 60, 40, 50],
        [50, 70, 70, 50, 70, 90, 50],
        [80, 50, 60, 40, 50, 40, 70],
        [30, 70, 30, 90, 70, 80, 60],
        [40, 60, 90, 60, 50, 70, 80],
        [80, 30, 50, 50, 80, 40, 60]], dtype=int64),
 array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
        '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object))

In [9]:
# 데이터 정규화 >> StandardScaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x)

x = scaler.transform(x) # 변환
x

array([[-1.26962211,  1.34164079, -0.8461218 , -0.98782916,  2.06644812,
         1.29927838, -0.59160798],
       [ 0.21160368, -0.36590203,  0.57536283, -0.3592106 ,  0.04805693,
        -0.09994449,  1.77482393],
       [-0.28213825, -0.93508297,  1.04919104,  0.26940795, -0.62474013,
         0.36646313,  1.18321596],
       [ 1.69282948, -0.36590203,  0.10153462, -1.61644772, -1.29753719,
        -1.96557498, -1.77482393],
       [-0.28213825,  0.77245985, -1.31995001,  0.89802651,  0.720854  ,
         0.83287076,  0.        ],
       [ 0.70534562, -1.50426391,  0.10153462, -0.98782916, -1.29753719,
        -1.03275974, -1.77482393],
       [-0.77588018,  1.91082173,  0.10153462,  0.26940795,  0.04805693,
         0.83287076,  0.        ],
       [-1.26962211,  0.20327891,  1.52301925,  0.26940795, -1.29753719,
         0.36646313,  0.59160798],
       [ 1.19908755, -0.93508297, -1.79377823,  1.52664507,  0.04805693,
        -1.03275974, -0.59160798],
       [-0.28213825,  0.7724

In [10]:
# knn 분류 모델 생성(범주형 데이터 분석)
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(x, y)

KNeighborsClassifier()

In [14]:
# 원래 데이터를 넣어서 예측

y_pred = classifier.predict(x)
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [12]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [15]:
# 모델을 평가

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y, y_pred))
print(classification_report(y, y_pred))

[[5 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

         1타입       1.00      1.00      1.00         5
         2타입       1.00      1.00      1.00         4
         3타입       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

