In [1]:
# -*- coding: utf-8 -*-

### 기본 라이브러리 불러오기
import pandas as pd
import numpy as np

In [2]:
uci_path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/\
breast-cancer-wisconsin/breast-cancer-wisconsin.data'

In [3]:
df = pd.read_csv(uci_path, header=None)
df.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       699 non-null    int64 
 1   1       699 non-null    int64 
 2   2       699 non-null    int64 
 3   3       699 non-null    int64 
 4   4       699 non-null    int64 
 5   5       699 non-null    int64 
 6   6       699 non-null    object
 7   7       699 non-null    int64 
 8   8       699 non-null    int64 
 9   9       699 non-null    int64 
 10  10      699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [5]:
# 열 이름 지정
df.columns = ['id','clump','cell_size','cell_shape', 'adhesion','epithlial',
              'bare_nuclei','chromatin','normal_nucleoli', 'mitoses', 'class'] 

#  IPython 디스플레이 설정 - 출력할 열의 개수 한도 늘리기
pd.set_option('display.max_columns', 15)


In [9]:
df.tail()

id  clump  cell_size  cell_shape  adhesion  epithlial bare_nuclei  \
694  776715      3          1           1         1          3           2   
695  841769      2          1           1         1          2           1   
696  888820      5         10          10         3          7           3   
697  897471      4          8           6         4          3           4   
698  897471      4          8           8         5          4           5   

     chromatin  normal_nucleoli  mitoses  class  
694          1                1        1      2  
695          1                1        1      2  
696          8               10        2      4  
697         10                6        1      4  
698         10                4        1      4

In [14]:
df.bare_nuclei.unique()

array(['1', '10', '2', '4', '3', '9', '7', '?', '5', '8', '6'],
      dtype=object)

In [16]:
df.bare_nuclei.replace('?', np.nan, inplace=True)
df.dropna(subset=['bare_nuclei'], axis=0, inplace=True)

In [24]:
df.bare_nuclei.unique()

array([ 1, 10,  2,  4,  3,  9,  7,  5,  8,  6], dtype=int64)

In [20]:
df.bare_nuclei = df.bare_nuclei.astype('int64')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               683 non-null    int64
 1   clump            683 non-null    int64
 2   cell_size        683 non-null    int64
 3   cell_shape       683 non-null    int64
 4   adhesion         683 non-null    int64
 5   epithlial        683 non-null    int64
 6   bare_nuclei      683 non-null    int64
 7   chromatin        683 non-null    int64
 8   normal_nucleoli  683 non-null    int64
 9   mitoses          683 non-null    int64
 10  class            683 non-null    int64
dtypes: int64(11)
memory usage: 64.0 KB


In [26]:
# 데이터 셋 구분
# 속성(변수) 선택
X=df[['clump','cell_size','cell_shape', 'adhesion','epithlial',
      'bare_nuclei','chromatin','normal_nucleoli', 'mitoses']]  #설명 변수 X
y=df['class']                                                   #예측 변수 Y

In [27]:
# 설명 변수 데이터 정규화

from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit(X).transform(X)

In [29]:
X

array([[ 0.19790469, -0.70221201, -0.74177362, ..., -0.18182716,
        -0.61292736, -0.34839971],
       [ 0.19790469,  0.27725185,  0.26278299, ..., -0.18182716,
        -0.28510482, -0.34839971],
       [-0.51164337, -0.70221201, -0.74177362, ..., -0.18182716,
        -0.61292736, -0.34839971],
       ...,
       [ 0.19790469,  2.23617957,  2.2718962 , ...,  1.86073779,
         2.33747554,  0.22916583],
       [-0.15686934,  1.58320366,  0.93248739, ...,  2.67776377,
         1.02618536, -0.34839971],
       [-0.15686934,  1.58320366,  1.6021918 , ...,  2.67776377,
         0.37054027, -0.34839971]])

In [31]:
# train data 와 test data로 구분(7:3 비율)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [33]:
X_train, X_train.shape

(array([[ 0.19790469,  1.58320366,  1.6021918 , ...,  1.4522248 ,
          1.68183045, -0.34839971],
        [ 0.55267873, -0.70221201, -0.74177362, ..., -0.99885314,
         -0.61292736, -0.34839971],
        [ 0.19790469, -0.70221201, -0.74177362, ..., -0.59034015,
         -0.61292736, -0.34839971],
        ...,
        [ 1.97177486,  0.6037398 ,  1.2673396 , ..., -0.18182716,
          0.04271773,  3.69455903],
        [-0.15686934, -0.70221201, -0.74177362, ..., -0.59034015,
         -0.61292736, -0.34839971],
        [ 1.97177486,  2.23617957,  2.2718962 , ...,  1.86073779,
          1.68183045,  3.69455903]]),
 (478, 9))

In [34]:
from sklearn import tree

In [35]:
# 모델 생성

model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [36]:
# train data로 모델 학습

model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [37]:
# test date로 예측 분류

y_hat = model.predict(X_test)
y_hat

array([4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 4, 2, 4, 2, 4, 4, 2,
       4, 2, 2, 2, 4, 4, 2, 4, 2, 4, 4, 4, 2, 2, 4, 2, 4, 4, 2, 4, 4, 2,
       2, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2,
       4, 4, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2,
       2, 2, 4, 4, 4, 2, 2], dtype=int64)

In [38]:
from sklearn.metrics import classification_report, confusion_matrix

In [39]:
confusion_matrix(y_test, y_hat)

array([[125,   2],
       [  5,  73]], dtype=int64)

In [41]:
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           2       0.96      0.98      0.97       127
           4       0.97      0.94      0.95        78

    accuracy                           0.97       205
   macro avg       0.97      0.96      0.96       205
weighted avg       0.97      0.97      0.97       205

