#### Pytorch wiki 참고
https://wikidocs.net/62306

## 02-01 파이토치 패키지의 기본

1. torch
메인 네임스페이스입니다. 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조를 가집니다.

2. torch.autograd
자동 미분을 위한 함수들이 포함되어져 있습니다. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function' 등이 포함되어져 있습니다.

3. torch.nn
신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어져 있습니다. 예를 들어 RNN, LSTM과 같은 레이어, ReLU와 같은 활성화 함수, MSELoss와 같은 손실 함수들이 있습니다.

4. torch.optim
확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현되어져 있습니다.

5. torch.utils.data
SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함되어져 있습니다.

6. torch.onnx
ONNX(Open Neural Network Exchange)의 포맷으로 모델을 익스포트(export)할 때 사용합니다. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷입니다.

## 02-02 텐서 조작하기

### 1. 벡터, 행렬 그리고 텐서(Vector, Matrix and Tensor)
- 벡터 : 1차원 텐서
- 행렬 : 2차원 텐서
- 텐서 : 3차원 이상의 텐서

### 2. 넘파이로 텐서 만들기

In [1]:
import numpy as np

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해 np.array로 1차원 array로 1차원 array호 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


- .ndim은 몇 차원인지를 출력합니다. 현재 백터이므로 1차원이 출력 됩니다.
- .shape는 크기를 췰력합니다. (7,)는 (1,7)을 의미합니다.

### 3. 파이토치 텐서 선언하기

#### 1D with PyTorch

In [4]:
import torch

In [5]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim())   # rank
print(t.shape) # shape
print(t.size())  # shape

1
torch.Size([7])
torch.Size([7])


- 현재 1차원 텐서이며, 원소는 7개입니다.

#### 2D with PyTorch

In [7]:
t = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9],
                      [10, 11, 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([4, 3])
torch.Size([4, 3])


#### 브로드캐스팅(Broadcasting)

In [9]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


- m1, m2의 크기가 같아 문제 없이 덧셈 연산이 가능

In [10]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


- 크기가 다른 텐서들 간의 연산 브로드캐스팅을 통해 이를 연산

In [11]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


- (1,2) (2,1) 텐서들 간의 연산 불가능하나 2x2 텐서로 만들어 연산 사용에 주의

#### 자주 사용되는 기능들

In [12]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


- matmul() 통해 행렬 곱셈 수행

In [13]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


- \* 또는 mul() 통해 element-wise, 동일 위치 원소 곱셈 수행

In [14]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [15]:
print(t.mean())

tensor(2.5000)


In [16]:
print(t.mean(dim=0))

tensor([2., 3.])


- mean 함수 내 dim 인자에 0을 주면 행 차원을 제거한다는 의미이다. 따라서 열 데이터 간의 평균 값이 나온다

In [17]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


- mean 함수 내 dim 인자에 1을 주면 열 차원을 제거한다는 의미이다. 따라서 행 데이터 간의 평균 값이 나온다

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.max()) # Returns one value: max

tensor(4.)


In [20]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


- dim 인자로 0을 주면 행 차원을 제거한 최대값 출력
- dim 인자를 주면 argmax도 함께 리턴하는 특징이 있음

## 02-03 텐서 조작하기2

### 4) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!

In [21]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [22]:
print(ft.shape)

torch.Size([2, 2, 3])


### 4-1) 3차원 텐서에서 2차원 텐서로 변경

In [23]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


- view는 기본적으로 변경 정과 변경 후의 텐서 안의 원소의 개수가 유지되어야 함
- view 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추함

### 4-2) 3차원 텐서의 크기 변경

In [24]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### 5) 스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [25]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [26]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


- 1이었던 두번째 차원이 제거됨

### 6) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [27]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [28]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


- 0번째 인덱스에 1인 차원을 추가함

- 요약: view(), squeeze(), unsqueeze()는 덴서의 원소 수를 그대로 유지하면서 모양과 차원을 조절한다.